[project]
name = 'chainhook-nft'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.nft-from-btc]
path = 'contracts/nft-from-btc.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
